// react-app/src/examples/state/ListExample.jsx
export default function List() {
  const items = [
    { message: "message1" },
    { message: "message2" },
    { message: "message3" },
    { message: "message4" },
  ];

  const listItems = items.map((item, index) => (
    <li key={item.message}>
      {index} - {item.message}
    </li>
  ));
  return <ul>{listItems}</ul>;
}

// vue-app/src/examples/state/ListExample.vue
<script setup>
import { ref } from 'vue'

const items = ref([
  { message: 'message1' },
  { message: 'message2' },
  { message: 'message3' },
  { message: 'message4' },
])
</script>

<template>
  <ul>
    <li v-for="(item, index) in items" :key="item.message">{{ index }} - {{ item.message }}</li>
  </ul>
</template>
